version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  build:
    commands:
      - echo "Compilando pagina..."
      - ls -la src/

artifacts:
  files:
    - src/index.html
    - src/style.css
  discard-paths: yes
