version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  build:
    commands:
      - echo "Compilando pagina..."
      - ls -la

artifacts:
  files:
    - pagina.html
    - style.css
  discard-paths: no
